name: Release Flutter App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  determine_version:
    name: Determine Next Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.semantic_release.outputs.new_release_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          tags: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Commitizen and Conventional Changelog
        run: |
          pip install --upgrade commitizen
          npm install -g conventional-changelog-conventionalcommits

      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Set up Git Authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

      - name: List Local Tags
        run: git tag

      - name: Show Tag Details
        run: |
          for tag in $(git tag); do
            echo "Tag: $tag"
            git show $tag --quiet
          done

      - name: Run Semantic Release
        id: semantic_release
        run: |
          cz bump --changelog --yes
          NEW_VERSION=$(cz version)
          echo "new_release_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: List Tags After Bump
        run: git tag

      - name: Push Changes and Tags
        run: |
          git push origin HEAD:main
          git push origin --tags
